language: go
install: true

go:
  - "1.10.x"
  - master

env:
  global:
    - GOARCH=amd64

before_install:
  - go get -u github.com/golang/dep

script:
  - chmod +x coverage.sh
  - go install -v ./... && ./coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)