language: go
install: true

go:
  - "1.10.x"
  - master

env:
  global:
    - GOARCH=amd64

notifications:
  email: false

before_install:
  - go get -u github.com/golang/dep

script:
  - chmod +x scripts/coverage.sh
  - go install -v ./... && ./scripts/coverage.sh
  - go test -v -race ./... 

after_success:
  - bash <(curl -s https://codecov.io/bash)