language: go
install: true

go:
  - "1.10.x"
  - master

env:
  global:
    - GOARCH=amd64

before_install:
  - go get -u github.com/golang/dep

after_success:
  - bash <(curl -s https://codecov.io/bash)