# Site params
title: TEMPest
description: A simple tool (CLI) that helps to handle, manage and act on temporary directories.

# config
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman

# pages
site.pages:
  - index
  - usage
  - about
  - install

# plugins
plugins:
  - jemoji
  - jekyll-seo-tag

url: https://chacas0.github.io/tempest

# last added
repository: ChacaS0/tempest
